name: Bundle
version: 1.0
author: ItmanHunter
main: com.ocoolcraft.plugins.BundleMain
description: Awesome plugin to create bundles
api-version: 1.13
commands:
  cbundle:
    permission: bundle.cbundle
    description: create a bundle with all items in your inventory
    usage: /cbundle <name>
  getbundle:
    permission: bundle.getbundle
    description: Gets a particular bundle.
    usage: /getbundle <name>